# Generated by Django 4.2.2 on 2023-07-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado_pedido',
            fields=[
                ('id_estado', models.AutoField(db_column='id_estado', primary_key=True, serialize=False)),
                ('nom_estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='id_pedido', primary_key=True, serialize=False)),
                ('total_pedido', models.FloatField()),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='myapp.estado_pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=30)),
                ('precio_producto', models.IntegerField()),
                ('stock', models.IntegerField(max_length=5)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='myapp.pedido')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='myapp.producto')),
            ],
        ),
    ]
